#!/bin/bash

NAME="serago-scraper"
DIR=/web_app/repos/SeraGo-Scraper
USER=neba
GROUP=neba
WORKERS=2
BIND=unix:/web_app/repos/SeraGo-Scraper/gunicorn.sock
DJANGO_SETTINGS_MODULE=serago.settings
DJANGO_WSGI_MODULE=serago.wsgi
LOG_LEVEL=error

cd $DIR
source .venv/bin/activate

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

exec .venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-
