# Generated by Django 6.1 on 2026-08-07 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('base_url', models.URLField(blank=True, default='', max_length=500)),
                ('scraper_type', models.CharField(choices=[('graphql', 'GraphQL (Hasura)'), ('nextjs', 'Next.js data API'), ('html', 'Server-side HTML'), ('playwright', 'Headless browser (Playwright)')], default='graphql', max_length=20)),
                ('endpoint', models.URLField(max_length=500)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='HTTP headers sent with every request to this source.')),
                ('query', models.TextField(blank=True, default='', help_text='GraphQL query (or API params) used to fetch listings.')),
                ('field_mapping', models.JSONField(blank=True, default=dict, help_text="Normalized field -> dotted path, e.g. {'external_id': 'id', 'title': 'title', 'description': {'path': 'description', 'transforms': ['strip_html']}}.")),
                ('pagination', models.JSONField(blank=True, default=dict, help_text='Pagination rules: page_size, results_path, variables, timeout...')),
                ('scrape_interval_hours', models.PositiveIntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['scraper_type', 'is_active'], name='src_type_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=16)),
                ('page', models.PositiveIntegerField(default=0, help_text='0-based page/offset index.')),
                ('items_found', models.PositiveIntegerField(default=0)),
                ('items_inserted', models.PositiveIntegerField(default=0)),
                ('items_updated', models.PositiveIntegerField(default=0)),
                ('items_skipped', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.source')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', '-started_at'], name='log_src_started_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScrapedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(help_text="The source's own id for this listing.", max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('job_type', models.CharField(blank=True, choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('REMOTE', 'Remote'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance'), ('TEMPORARY', 'Temporary'), ('OTHER', 'Other')], default='', max_length=32)),
                ('url', models.URLField(blank=True, default='', max_length=1000)),
                ('salary', models.CharField(blank=True, default='', max_length=255)),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 of title|company|location|job_type.', max_length=64)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Original payload for this item.')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='False once the listing disappears from the source.')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.source')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['source', 'is_active'], name='item_src_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_source_external_id')],
            },
        ),
    ]
