# Generated by Django 6.1 on 2026-08-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeditem',
            name='job_number',
            field=models.PositiveIntegerField(blank=True, help_text='Per-day sequential number (01, 02, ...), resetting each day.', null=True),
        ),
        migrations.AddField(
            model_name='scrapeditem',
            name='numbered_on',
            field=models.DateField(blank=True, help_text='Local day this item was numbered on.', null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='only_today',
            field=models.BooleanField(default=True, help_text="Only scrape listings dated today. Requires a 'date_filter' key in pagination rules (field + from_var/to_var names)."),
        ),
        migrations.AlterField(
            model_name='scrapeditem',
            name='job_type',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('CONTRACTUAL', 'Contractual'), ('REMOTE', 'Remote'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance'), ('TEMPORARY', 'Temporary'), ('OTHER', 'Other')], default='', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='scrapeditem',
            constraint=models.UniqueConstraint(fields=('source', 'numbered_on', 'job_number'), name='uniq_source_day_job_number'),
        ),
    ]
