# Generated by Django 6.1 on 2026-08-07 08:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_scrapeditem_job_number_scrapeditem_numbered_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfriworkJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('job_type', models.CharField(blank=True, choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('CONTRACTUAL', 'Contractual'), ('REMOTE', 'Remote'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance'), ('TEMPORARY', 'Temporary'), ('OTHER', 'Other')], default='', max_length=32)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('api_created_at', models.DateTimeField(blank=True, help_text="The API's own created_at timestamp.", null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='scrapeditem',
            options={'ordering': ['-numbered_on', 'job_number']},
        ),
        migrations.AddField(
            model_name='scrapelog',
            name='api_hits',
            field=models.PositiveIntegerField(default=0, help_text='Number of HTTP requests made during this run.'),
        ),
        migrations.AddField(
            model_name='scrapelog',
            name='pages_hit',
            field=models.JSONField(blank=True, default=list, help_text="Pages fetched during this run, e.g. [{'page': 0, 'http_status': 200, 'found': 10}]."),
        ),
        migrations.AddField(
            model_name='scrapeditem',
            name='afriwork_job',
            field=models.OneToOneField(blank=True, help_text='Afriwork-specific detail row for this listing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_item_master', to='core.afriworkjob'),
        ),
        migrations.CreateModel(
            name='AfriworkScrapeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_calls', models.JSONField(blank=True, default=list, help_text="Detailed API calls: [{'page': 0, 'http_status': 200, 'requested_at': '...'}].")),
                ('query', models.TextField(blank=True, default='', help_text='The GraphQL query sent.')),
                ('scrape_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='afriwork_log', to='core.scrapelog')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
