# Generated by Django 6.1 on 2026-08-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_afriworkjob_alter_scrapeditem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afriworkjob',
            options={'ordering': ['-numbered_on', 'job_number']},
        ),
        migrations.AddField(
            model_name='afriworkjob',
            name='job_number',
            field=models.PositiveIntegerField(blank=True, help_text='Per-day sequential number, mirroring ScrapedItem.job_number.', null=True),
        ),
        migrations.AddField(
            model_name='afriworkjob',
            name='numbered_on',
            field=models.DateField(blank=True, help_text='Local day this job was numbered on.', null=True),
        ),
    ]
