# Generated by Django 6.1 on 2026-08-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_afriworkjob_options_afriworkjob_job_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afriworkjob',
            name='api_updated_at',
            field=models.DateTimeField(blank=True, help_text="The API's own updated_at timestamp.", null=True),
        ),
        migrations.AddField(
            model_name='afriworkjob',
            name='approval_status',
            field=models.CharField(blank=True, default='', help_text='PUBLISHED / REFRESHED / ...', max_length=32),
        ),
        migrations.AddField(
            model_name='afriworkjob',
            name='compensation_amount_cents',
            field=models.BigIntegerField(blank=True, help_text='Compensation in cents (ETB) when the API provides it.', null=True),
        ),
        migrations.AddField(
            model_name='afriworkjob',
            name='compensation_currency',
            field=models.CharField(blank=True, default='', help_text='ETB / USD / ...', max_length=16),
        ),
        migrations.AddField(
            model_name='afriworkjob',
            name='compensation_type',
            field=models.CharField(blank=True, default='', help_text='MONTHLY / FIXED / ...', max_length=32),
        ),
        migrations.AddField(
            model_name='afriworkjob',
            name='country',
            field=models.CharField(blank=True, default='', help_text='Country name (from city.country.name).', max_length=255),
        ),
        migrations.AddField(
            model_name='afriworkjob',
            name='entity_name',
            field=models.CharField(blank=True, default='', help_text='The posting company/client name.', max_length=255),
        ),
        migrations.AddField(
            model_name='afriworkjob',
            name='entity_type',
            field=models.CharField(blank=True, default='', help_text='company / private_client / ...', max_length=32),
        ),
        migrations.AddField(
            model_name='afriworkjob',
            name='experience_level',
            field=models.CharField(blank=True, default='', help_text='ENTRY / JUNIOR / SENIOR / ...', max_length=32),
        ),
        migrations.AddField(
            model_name='afriworkjob',
            name='job_site',
            field=models.CharField(blank=True, default='', help_text='ONSITE / REMOTE / HYBRID.', max_length=32),
        ),
        migrations.AddField(
            model_name='afriworkjob',
            name='refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afriworkjob',
            name='sectors',
            field=models.JSONField(blank=True, default=list, help_text="Sector names, e.g. ['Marketing']."),
        ),
        migrations.AddField(
            model_name='afriworkjob',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text="Skill names, e.g. ['Canva', 'Adobe Illustrator']."),
        ),
        migrations.AlterField(
            model_name='afriworkjob',
            name='location',
            field=models.CharField(blank=True, default='', help_text='City name (from city.name).', max_length=255),
        ),
    ]
