# Generated by Django 6.1 on 2026-08-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_afriworkjob_api_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='only_today',
            field=models.BooleanField(default=True, help_text="Only scrape listings dated today (published or refreshed today). Requires a 'date_filter' key in pagination rules (field + from_var/to_var names); the query decides how the bounds apply."),
        ),
    ]
