# Generated by Django 6.1 on 2026-08-07 09:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_source_only_today'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeDayLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField(help_text='The local day this rollup covers.', unique=True)),
                ('run_count', models.PositiveIntegerField(default=0, help_text='Total runs across all sources this day.')),
                ('api_hits', models.PositiveIntegerField(default=0, help_text='Total API requests across all sources this day.')),
                ('items_found', models.PositiveIntegerField(default=0)),
                ('items_inserted', models.PositiveIntegerField(default=0)),
                ('items_updated', models.PositiveIntegerField(default=0)),
                ('items_skipped', models.PositiveIntegerField(default=0)),
                ('per_source', models.JSONField(blank=True, default=list, help_text="Per-source summaries: [{'source': slug, 'name', 'run_count', 'api_hits', 'items_*'}].")),
                ('scraped_log', models.JSONField(blank=True, default=list, help_text='Every run that day, each tagged with its source slug.')),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
        migrations.AlterModelOptions(
            name='afriworkscrapelog',
            options={'ordering': ['-day']},
        ),
        migrations.RemoveField(
            model_name='afriworkscrapelog',
            name='api_calls',
        ),
        migrations.RemoveField(
            model_name='afriworkscrapelog',
            name='query',
        ),
        migrations.RemoveField(
            model_name='afriworkscrapelog',
            name='scrape_log',
        ),
        migrations.AddField(
            model_name='afriworkscrapelog',
            name='api_hits',
            field=models.PositiveIntegerField(default=0, help_text='Total API requests made this day.'),
        ),
        migrations.AddField(
            model_name='afriworkscrapelog',
            name='day',
            field=models.DateField(db_index=True, help_text='The local day this rollup covers.', null=True),
        ),
        migrations.AddField(
            model_name='afriworkscrapelog',
            name='items_found',
            field=models.PositiveIntegerField(default=0, help_text='Total items found this day.'),
        ),
        migrations.AddField(
            model_name='afriworkscrapelog',
            name='items_inserted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='afriworkscrapelog',
            name='items_skipped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='afriworkscrapelog',
            name='items_updated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='afriworkscrapelog',
            name='run_count',
            field=models.PositiveIntegerField(default=0, help_text='How many scrape runs happened this day.'),
        ),
        migrations.AddField(
            model_name='afriworkscrapelog',
            name='scraped_log',
            field=models.JSONField(blank=True, default=list, help_text='One summary entry per scrape run that day (grows as we scrape).'),
        ),
        migrations.AddField(
            model_name='afriworkscrapelog',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='afriwork_day_logs', to='core.source'),
        ),
        migrations.AddConstraint(
            model_name='afriworkscrapelog',
            constraint=models.UniqueConstraint(fields=('source', 'day'), name='uniq_afriwork_daylog_src_day'),
        ),
    ]
