# Generated by Django 6.1 on 2026-08-07 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_scrapedaylog_alter_afriworkscrapelog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afriworkscrapelog',
            name='day',
            field=models.DateField(db_index=True, help_text='The local day this rollup covers.'),
        ),
        migrations.AlterField(
            model_name='afriworkscrapelog',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afriwork_day_logs', to='core.source'),
        ),
    ]
