# Generated by Django 6.1 on 2026-08-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_afriworkscrapelog_day_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapeDayLog',
        ),
        migrations.AlterModelOptions(
            name='scrapelog',
            options={'ordering': ['-day']},
        ),
        migrations.RemoveIndex(
            model_name='scrapelog',
            name='log_src_started_idx',
        ),
        migrations.AddField(
            model_name='afriworkscrapelog',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', help_text="Worst status across the day's runs.", max_length=16),
        ),
        migrations.AddField(
            model_name='scrapelog',
            name='day',
            field=models.DateField(help_text='The local day this master log covers.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='scrapelog',
            name='run_count',
            field=models.PositiveIntegerField(default=0, help_text='Total scrape runs across all websites this day.'),
        ),
        migrations.AddField(
            model_name='scrapelog',
            name='scraped_log',
            field=models.JSONField(blank=True, default=list, help_text='Every run that day, each tagged with its source slug.'),
        ),
        migrations.AddField(
            model_name='scrapelog',
            name='websites',
            field=models.JSONField(blank=True, default=list, help_text="Per-website buckets: [{'source', 'name', 'log_id', 'run_count', 'api_hits', 'items_*'}]. log_id references the site's own log (e.g. AfriworkScrapeLog pk)."),
        ),
        migrations.AlterField(
            model_name='scrapelog',
            name='api_hits',
            field=models.PositiveIntegerField(default=0, help_text='Total API requests across all websites this day.'),
        ),
        migrations.AlterField(
            model_name='scrapelog',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', help_text="Worst status across the day's runs.", max_length=16),
        ),
        migrations.RemoveField(
            model_name='scrapelog',
            name='duration_ms',
        ),
        migrations.RemoveField(
            model_name='scrapelog',
            name='errors',
        ),
        migrations.RemoveField(
            model_name='scrapelog',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='scrapelog',
            name='message',
        ),
        migrations.RemoveField(
            model_name='scrapelog',
            name='page',
        ),
        migrations.RemoveField(
            model_name='scrapelog',
            name='pages_hit',
        ),
        migrations.RemoveField(
            model_name='scrapelog',
            name='source',
        ),
        migrations.RemoveField(
            model_name='scrapelog',
            name='started_at',
        ),
    ]
