# Generated by Django 6.1 on 2026-08-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_scrapedaylog_alter_scrapelog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapelog',
            name='day',
            field=models.DateField(help_text='The local day this master log covers.', unique=True),
        ),
    ]
