# Generated by Django 6.1 on 2026-08-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_scrapelog_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapelog',
            name='websites',
            field=models.JSONField(blank=True, default=list, help_text="Per-website buckets: [{'source', 'name', 'table', 'log_id', 'status', 'run_count', 'api_hits', 'items_*', 'scraped_log'}]. table + log_id reference the site's own log (e.g. AfriworkScrapeLog pk); scraped_log is that site's FULL log data for the day (every run's pages hit, http statuses, errors)."),
        ),
    ]
