# Generated by Django 6.1 on 2026-08-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_scrapelog_websites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapelog',
            name='scraped_log',
        ),
        migrations.AlterField(
            model_name='scrapelog',
            name='websites',
            field=models.JSONField(blank=True, default=list, help_text="Short per-website buckets: [{'source', 'name', 'table', 'log_id', 'status', 'run_count', 'api_hits', 'items_*'}]. table + log_id reference the site's own log (e.g. AfriworkScrapeLog pk) where the full run detail lives."),
        ),
    ]
