# Generated by Django 6.1 on 2026-08-07 11:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_scrapelog_scraped_log_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthioJobsJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(help_text="The API's opaque encrypted job id.", max_length=500, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.CharField(blank=True, default='', help_text="URL slug, e.g. 'asJrYsRdI8-senior-international-banking-officer'.", max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('state', models.CharField(blank=True, default='', help_text="State/region, e.g. 'Addis Ababa'.", max_length=255)),
                ('type', models.PositiveIntegerField(blank=True, help_text='Numeric job type code from the API.', null=True)),
                ('level', models.CharField(blank=True, default='', help_text="Experience level code, e.g. '3'.", max_length=32)),
                ('location_type', models.CharField(blank=True, default='', help_text='Office / Remote / Hybrid / ...', max_length=64)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, help_text='date_expiry from the API.', null=True)),
                ('catalogs', models.JSONField(blank=True, default=list, help_text='[{id, name, options}] category list, e.g. Banking and Insurance.')),
                ('company', models.JSONField(blank=True, default=dict, help_text='The full company object the API returns (name, slug, logo, ...).')),
                ('application_method', models.CharField(blank=True, default='', help_text='ATS / EMAIL / CAREER_PAGE_LINK / IN_PERSON / ...', max_length=64)),
                ('application_email', models.EmailField(blank=True, default='', max_length=255)),
                ('career_page_link', models.URLField(blank=True, default='', max_length=1000)),
                ('application_form', models.JSONField(blank=True, help_text='Embedded application form payload when present.', null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('job_number', models.PositiveIntegerField(blank=True, help_text='Per-day sequential number, mirroring ScrapedItem.job_number.', null=True)),
                ('numbered_on', models.DateField(blank=True, help_text='Local day this job was numbered on.', null=True)),
            ],
            options={
                'ordering': ['-numbered_on', 'job_number'],
            },
        ),
        migrations.AlterField(
            model_name='source',
            name='scraper_type',
            field=models.CharField(choices=[('graphql', 'GraphQL (Hasura)'), ('rest', 'REST JSON API'), ('nextjs', 'Next.js data API'), ('html', 'Server-side HTML'), ('playwright', 'Headless browser (Playwright)')], default='graphql', max_length=20),
        ),
        migrations.AddField(
            model_name='scrapeditem',
            name='ethiojobs_job',
            field=models.OneToOneField(blank=True, help_text='EthioJobs-specific detail row for this listing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_item_master', to='core.ethiojobsjob'),
        ),
        migrations.CreateModel(
            name='EthioJobsScrapeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField(db_index=True, help_text='The local day this rollup covers.')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', help_text="Worst status across the day's runs.", max_length=16)),
                ('run_count', models.PositiveIntegerField(default=0, help_text='How many scrape runs happened this day.')),
                ('api_hits', models.PositiveIntegerField(default=0, help_text='Total API requests made this day.')),
                ('items_found', models.PositiveIntegerField(default=0, help_text='Total items found this day.')),
                ('items_inserted', models.PositiveIntegerField(default=0)),
                ('items_updated', models.PositiveIntegerField(default=0)),
                ('items_skipped', models.PositiveIntegerField(default=0)),
                ('scraped_log', models.JSONField(blank=True, default=list, help_text='One summary entry per scrape run that day (grows as we scrape).')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ethiojobs_day_logs', to='core.source')),
            ],
            options={
                'ordering': ['-day'],
                'constraints': [models.UniqueConstraint(fields=('source', 'day'), name='uniq_ethiojobs_daylog_src_day')],
            },
        ),
    ]
