# Generated by Django 6.1 on 2026-08-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ethiojobsjob_alter_source_scraper_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethiojobsjob',
            name='api_id',
            field=models.TextField(blank=True, default='', help_text="The API's opaque encrypted job id (rotates every request; kept for reference)."),
        ),
        migrations.AlterField(
            model_name='ethiojobsjob',
            name='external_id',
            field=models.CharField(help_text='Dedup key — the stable job slug (the encrypted id rotates per request).', max_length=500, unique=True),
        ),
    ]
