# Generated by Django 6.1 on 2026-08-07 11:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_ethiojobsjob_api_id_alter_ethiojobsjob_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaHuJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='', help_text='The job summary from the API.')),
                ('type', models.CharField(blank=True, choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('CONTRACTUAL', 'Contractual'), ('REMOTE', 'Remote'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance'), ('TEMPORARY', 'Temporary'), ('OTHER', 'Other')], default='', help_text='full_time / contract / internship / ... (normalized).', max_length=32)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('max_years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly salary in ETB when the API provides it.', max_digits=14, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('expired', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, default='', help_text="The API's free-text location string, if any.", max_length=255)),
                ('source', models.CharField(blank=True, default='', help_text='Aggregator source, e.g. hahujobs_telegram / hahujobs_enterprise / addis_zemen_gazette.', max_length=64)),
                ('application_method', models.CharField(blank=True, default='', help_text='link / email / in_person / hahujobs_primary / ...', max_length=64)),
                ('application_url', models.URLField(blank=True, default='', max_length=1000)),
                ('application_email', models.EmailField(blank=True, default='', max_length=255)),
                ('number_of_applicants', models.PositiveIntegerField(blank=True, null=True)),
                ('approved_on', models.DateTimeField(blank=True, db_index=True, help_text='When the aggregator approved/listed the job (published_at analog).', null=True)),
                ('total_web_view_count', models.PositiveIntegerField(default=0)),
                ('telegram_view_count', models.PositiveIntegerField(default=0)),
                ('total_view_count', models.PositiveIntegerField(default=0)),
                ('entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('entity_name', models.CharField(blank=True, default='', help_text='The posting company.', max_length=255)),
                ('entity_logo', models.URLField(blank=True, default='', max_length=1000)),
                ('sector_id', models.CharField(blank=True, default='', max_length=64)),
                ('sector_name', models.CharField(blank=True, default='', max_length=255)),
                ('sector_icon_class', models.CharField(blank=True, default='', max_length=64)),
                ('sector_icon_code', models.CharField(blank=True, default='', max_length=16)),
                ('sub_sector_name', models.CharField(blank=True, default='', max_length=255)),
                ('area_name', models.CharField(blank=True, default='', max_length=255)),
                ('area_address', models.CharField(blank=True, default='', max_length=500)),
                ('isco_08_code', models.CharField(blank=True, default='', max_length=16)),
                ('isco_08_title_en', models.CharField(blank=True, default='', max_length=500)),
                ('isco_08_title_am', models.CharField(blank=True, default='', max_length=500)),
                ('soc_2010_title', models.CharField(blank=True, default='', max_length=500)),
                ('soc_2010_onetsoc_code', models.CharField(blank=True, default='', max_length=32)),
                ('esco_code', models.CharField(blank=True, default='', max_length=32)),
                ('cities', models.JSONField(blank=True, default=list, help_text="City names, e.g. ['Addis Ababa'].")),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('job_number', models.PositiveIntegerField(blank=True, help_text='Per-day sequential number, mirroring ScrapedItem.job_number.', null=True)),
                ('numbered_on', models.DateField(blank=True, help_text='Local day this job was numbered on.', null=True)),
            ],
            options={
                'ordering': ['-numbered_on', 'job_number'],
            },
        ),
        migrations.AddField(
            model_name='scrapeditem',
            name='hahujobs_job',
            field=models.OneToOneField(blank=True, help_text='HaHuJobs-specific detail row for this listing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_item_master', to='core.hahujob'),
        ),
        migrations.CreateModel(
            name='HaHuScrapeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField(db_index=True, help_text='The local day this rollup covers.')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', help_text="Worst status across the day's runs.", max_length=16)),
                ('run_count', models.PositiveIntegerField(default=0, help_text='How many scrape runs happened this day.')),
                ('api_hits', models.PositiveIntegerField(default=0, help_text='Total API requests made this day.')),
                ('items_found', models.PositiveIntegerField(default=0, help_text='Total items found this day.')),
                ('items_inserted', models.PositiveIntegerField(default=0)),
                ('items_updated', models.PositiveIntegerField(default=0)),
                ('items_skipped', models.PositiveIntegerField(default=0)),
                ('scraped_log', models.JSONField(blank=True, default=list, help_text='One summary entry per scrape run that day (grows as we scrape).')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hahujobs_day_logs', to='core.source')),
            ],
            options={
                'ordering': ['-day'],
                'constraints': [models.UniqueConstraint(fields=('source', 'day'), name='uniq_hahujobs_daylog_src_day')],
            },
        ),
    ]
