# Generated by Django 6.1 on 2026-08-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_hahujob_scrapeditem_hahujobs_job_hahuscrapelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hahujob',
            name='location',
            field=models.CharField(blank=True, default='', help_text="The API's free-text location string, if any.", max_length=500),
        ),
    ]
