# Generated by Django 6.1 on 2026-08-07 12:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_hahujob_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeezJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(help_text='Dedup key — the job-detail slug from the listing URL.', max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.CharField(blank=True, default='', help_text="URL slug, e.g. 'office-engineer-4b-trading-plc'.", max_length=500)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('company_logo', models.URLField(blank=True, default='', help_text='Company logo URL from the card (cards without a logo show a letter placeholder).', max_length=1000)),
                ('location', models.CharField(blank=True, default='', help_text="City/area from the card, e.g. 'Addis Ababa' or 'Kality, Addis Ababa'.", max_length=255)),
                ('country', models.CharField(blank=True, default='', help_text="Country shown on the card (usually 'Ethiopia').", max_length=64)),
                ('deadline', models.DateTimeField(blank=True, help_text="Parsed from the card's deadline text.", null=True)),
                ('deadline_text', models.CharField(blank=True, default='', help_text="Raw card text, e.g. 'Deadline: September 7, 2026'.", max_length=128)),
                ('employment_text', models.CharField(blank=True, default='', help_text="Raw chip, e.g. 'Full-time / Permanent'.", max_length=128)),
                ('job_time', models.CharField(blank=True, default='', help_text="Site's job-time filter value: full_time / part_time.", max_length=32)),
                ('job_type', models.CharField(blank=True, default='', help_text="Site's job-type filter value: permanent / contract / internship / freelance / volunteer.", max_length=32)),
                ('experience_text', models.CharField(blank=True, default='', help_text="Raw chip, e.g. '3+ Years' or '2/3 Years'.", max_length=64)),
                ('min_experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('max_experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('posted_text', models.CharField(blank=True, default='', help_text="Raw chip, e.g. 'Posted: 3 min ago'.", max_length=64)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text="Estimated from the 'Posted: X ago' chip (the site exposes no exact timestamps).", null=True)),
                ('url', models.URLField(blank=True, default='', help_text='Absolute job-detail URL.', max_length=1000)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='The parsed card fields (raw HTML-derived data).')),
                ('job_number', models.PositiveIntegerField(blank=True, help_text='Per-day sequential number, mirroring ScrapedItem.job_number.', null=True)),
                ('numbered_on', models.DateField(blank=True, help_text='Local day this job was numbered on.', null=True)),
            ],
            options={
                'ordering': ['-numbered_on', 'job_number'],
            },
        ),
        migrations.AddField(
            model_name='scrapeditem',
            name='geezjobs_job',
            field=models.OneToOneField(blank=True, help_text='GeezJobs-specific detail row for this listing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_item_master', to='core.geezjob'),
        ),
        migrations.CreateModel(
            name='GeezScrapeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField(db_index=True, help_text='The local day this rollup covers.')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', help_text="Worst status across the day's runs.", max_length=16)),
                ('run_count', models.PositiveIntegerField(default=0, help_text='How many scrape runs happened this day.')),
                ('api_hits', models.PositiveIntegerField(default=0, help_text='Total API requests made this day.')),
                ('items_found', models.PositiveIntegerField(default=0, help_text='Total items found this day.')),
                ('items_inserted', models.PositiveIntegerField(default=0)),
                ('items_updated', models.PositiveIntegerField(default=0)),
                ('items_skipped', models.PositiveIntegerField(default=0)),
                ('scraped_log', models.JSONField(blank=True, default=list, help_text='One summary entry per scrape run that day (grows as we scrape).')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geezjobs_day_logs', to='core.source')),
            ],
            options={
                'ordering': ['-day'],
                'constraints': [models.UniqueConstraint(fields=('source', 'day'), name='uniq_geezjobs_daylog_src_day')],
            },
        ),
    ]
