# Generated by Django 6.1 on 2026-08-07 13:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_geezjob_scrapeditem_geezjobs_job_geezscrapelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporterJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(help_text='Dedup key — the WordPress post id from the listing URL.', max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, default='', help_text='Absolute job-detail URL.', max_length=1000)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', help_text="City/area from the card, e.g. 'Addis Ababa'.", max_length=255)),
                ('job_type_text', models.CharField(blank=True, default='', help_text="Raw card chip, e.g. 'Full Time'.", max_length=64)),
                ('job_type', models.CharField(blank=True, default='', help_text="Site's normalized job-type value: full_time / part_time / contract / internship / freelance / temporary / ...", max_length=32)),
                ('posted_text', models.CharField(blank=True, default='', help_text="Raw card date text, e.g. 'August 5, 2026'.", max_length=64)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text="Exact timestamp from the card's <time datetime> attribute.", null=True)),
                ('deadline_text', models.CharField(blank=True, default='', help_text="Raw closing date text, e.g. 'August 12, 2026'.", max_length=64)),
                ('deadline', models.DateTimeField(blank=True, help_text="Parsed from the card's closing date.", null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='The parsed card fields (raw HTML-derived data).')),
                ('job_number', models.PositiveIntegerField(blank=True, help_text='Per-day sequential number, mirroring ScrapedItem.job_number.', null=True)),
                ('numbered_on', models.DateField(blank=True, help_text='Local day this job was numbered on.', null=True)),
            ],
            options={
                'ordering': ['-numbered_on', 'job_number'],
            },
        ),
        migrations.AddField(
            model_name='scrapeditem',
            name='reporter_job',
            field=models.OneToOneField(blank=True, help_text='Ethiopian Reporter Jobs-specific detail row for this listing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_item_master', to='core.reporterjob'),
        ),
        migrations.CreateModel(
            name='ReporterScrapeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField(db_index=True, help_text='The local day this rollup covers.')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', help_text="Worst status across the day's runs.", max_length=16)),
                ('run_count', models.PositiveIntegerField(default=0, help_text='How many scrape runs happened this day.')),
                ('api_hits', models.PositiveIntegerField(default=0, help_text='Total API requests made this day.')),
                ('items_found', models.PositiveIntegerField(default=0, help_text='Total items found this day.')),
                ('items_inserted', models.PositiveIntegerField(default=0)),
                ('items_updated', models.PositiveIntegerField(default=0)),
                ('items_skipped', models.PositiveIntegerField(default=0)),
                ('scraped_log', models.JSONField(blank=True, default=list, help_text='One summary entry per scrape run that day (grows as we scrape).')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporterjobs_day_logs', to='core.source')),
            ],
            options={
                'ordering': ['-day'],
                'constraints': [models.UniqueConstraint(fields=('source', 'day'), name='uniq_reporterjobs_daylog_src_day')],
            },
        ),
    ]
