# Generated by Django 6.1 on 2026-08-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_reporterjob_scrapeditem_reporter_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapelog',
            name='runs',
            field=models.JSONField(blank=True, default=list, help_text="One compact entry per overall scrape sweep (the 2 daily scrape_all runs): {run, time, hits, found, inserted, updated, skipped, status}. Per-site day logs hold the full detail; this is the short 'what happened this run' summary."),
        ),
    ]
