# Generated by Django 6.1 on 2026-08-15 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_scrapelog_runs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeditem',
            name='raw_data',
        ),
    ]
