# Generated by Django 6.1 on 2026-08-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_scrapeditem_raw_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeditem',
            name='content_hash',
            field=models.CharField(db_index=True, help_text='SHA-256 of title|company|location|job_type|url.', max_length=64),
        ),
        migrations.AddIndex(
            model_name='scrapeditem',
            index=models.Index(fields=['updated_at'], name='item_updated_at_idx'),
        ),
    ]
