# Generated by Django 6.1 on 2026-08-16 08:56

from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone


def backfill_missing_deadlines(apps, schema_editor):
    """Give every existing row without a deadline one (published + 30 days),
    exactly as the scraper's save path does for new listings. Without this,
    the deadline+7-day lifecycle (hide from the feed, then archive) would
    never apply to the rows already in the database.
    """
    ScrapedItem = apps.get_model("core", "ScrapedItem")
    for item in ScrapedItem.objects.filter(deadline__isnull=True).iterator():
        base = item.published_at or item.created_at or timezone.now()
        item.deadline = base + timedelta(days=30)
        item.deadline_is_default = True
        item.save(update_fields=["deadline", "deadline_is_default", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_scrapeditem_content_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeditem',
            name='deadline_is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_missing_deadlines, migrations.RunPython.noop),
    ]
