# Generated by Django 6.1 on 2026-08-16 10:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_scrapeditem_deadline_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_on', models.DateField(help_text='The Sunday the archived week ended (the files cover Mon–Sun up to this day).', unique=True)),
                ('jobs_file', models.CharField(blank=True, default='', help_text='Sent jobs filename, e.g. jobs-2026-08-16.jsonl.gz.', max_length=255)),
                ('logs_file', models.CharField(blank=True, default='', help_text='Sent logs filename, e.g. logs-2026-08-16.json.gz.', max_length=255)),
                ('jobs_count', models.PositiveIntegerField(default=0, help_text='How many ended jobs the jobs file contained.')),
                ('log_rows', models.PositiveIntegerField(default=0, help_text='How many master + per-site log rows the logs file contained.')),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When both files finished uploading.')),
            ],
            options={
                'ordering': ['-archived_on'],
            },
        ),
    ]
