# Generated by Django 6.1 on 2026-08-16 11:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_archiverun'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_type', models.CharField(choices=[('week', 'Week'), ('month', 'Month')], max_length=8)),
                ('period_start', models.DateField(help_text='Monday for a week; the 1st for a month.')),
                ('period_end', models.DateField(help_text='Sunday for a week; the last day for a month.')),
                ('days_with_runs', models.PositiveIntegerField(default=0, help_text='How many days in the period recorded logs.')),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('api_hits', models.PositiveIntegerField(default=0)),
                ('items_found', models.PositiveIntegerField(default=0)),
                ('items_inserted', models.PositiveIntegerField(default=0)),
                ('items_updated', models.PositiveIntegerField(default=0)),
                ('items_skipped', models.PositiveIntegerField(default=0)),
                ('runs_by_status', models.JSONField(blank=True, default=dict, help_text='{"success": N, "partial": N, "failed": N} across all per-site runs in the period.')),
                ('top_errors', models.JSONField(blank=True, default=list, help_text='Most common run error messages: [{"message": ..., "count": N}] (top 5).')),
                ('by_source', models.JSONField(blank=True, default=dict, help_text='Per-source aggregates: {slug: {run_count, api_hits, items_*, days_with_runs, failed_runs}}.')),
            ],
            options={
                'ordering': ['-period_start'],
                'constraints': [models.UniqueConstraint(fields=('period_type', 'period_start'), name='uniq_scrapestat_type_start')],
            },
        ),
    ]
