# Generated by Django 6.1 on 2026-08-16 17:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_fix_defaulted_geez_deadlines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapestat',
            name='period_type',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=8),
        ),
        migrations.CreateModel(
            name='CategoryStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_type', models.CharField(help_text="The normalized dimension, e.g. 'sector' (future: 'job', ...).", max_length=16)),
                ('period_start', models.DateField(db_index=True, help_text='The local day these counts were computed for.')),
                ('category_name', models.CharField(help_text='Sector (or category) name.', max_length=255)),
                ('count', models.PositiveIntegerField(default=0, help_text='Jobs in this category found that day.')),
            ],
            options={
                'ordering': ['-period_start', '-count'],
                'indexes': [models.Index(fields=['category_type', 'period_start'], name='catstat_type_day_idx')],
                'constraints': [models.UniqueConstraint(fields=('category_type', 'period_start', 'category_name'), name='uniq_categorystat_type_day_name')],
            },
        ),
    ]
