# Generated by Django 6.1 on 2026-08-18 11:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_scrapestat_period_type_categorystat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperCreditUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(choices=[('zenrows', 'ZenRows'), ('scrapedo', 'Scrape.do'), ('scrapebadger', 'ScrapeBadger'), ('scrapfly', 'ScrapFly'), ('scraperapi', 'ScraperAPI')], max_length=20)),
                ('credits_used', models.PositiveIntegerField(default=0)),
                ('month', models.CharField(help_text='YYYY-MM — resets each calendar month', max_length=7)),
                ('source_slug', models.SlugField(blank=True, default='', help_text='Which source triggered this credit use', max_length=120)),
            ],
            options={
                'verbose_name': 'Scraper credit usage',
                'verbose_name_plural': 'Scraper credit usage',
                'indexes': [models.Index(fields=['service', 'month'], name='credit_svc_month_idx')],
            },
        ),
    ]
