# Generated by Django 6.1 on 2026-08-21 15:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_scrapercreditusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapercreditusage',
            name='service',
            field=models.CharField(choices=[('scrapedo', 'ScrapeDo'), ('scrapebadger', 'ScrapeBadger'), ('zenrows', 'ZenRows'), ('scraperapi', 'ScraperAPI'), ('scrapfly', 'ScrapFly'), ('jina', 'JinaReader'), ('firecrawl', 'Firecrawl'), ('playwright', 'Playwright')], max_length=20),
        ),
        migrations.CreateModel(
            name='NormalizedJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_slug', models.SlugField(help_text="Source website slug, e.g. 'afriwork'.", max_length=120)),
                ('external_id', models.CharField(help_text="The source's own id for this listing (dedup key with source_slug).", max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('job_type', models.CharField(blank=True, choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('CONTRACTUAL', 'Contractual'), ('REMOTE', 'Remote'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance'), ('TEMPORARY', 'Temporary'), ('OTHER', 'Other')], default='', help_text='FULL_TIME / PART_TIME / CONTRACT / ...', max_length=32)),
                ('url', models.URLField(blank=True, default='', max_length=1000)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('deadline_is_default', models.BooleanField(default=False, help_text='True when the source provided no deadline and the scraper defaulted.')),
                ('is_active', models.BooleanField(default=True, help_text='False once the listing disappears from the source.')),
                ('description', models.TextField(blank=True, default='', help_text='HTML-stripped job description.')),
                ('company_logo_url', models.URLField(blank=True, default='', help_text='Company logo URL from the source.', max_length=1000)),
                ('work_mode', models.CharField(blank=True, default='', help_text='ONSITE / REMOTE / HYBRID (when the source provides it).', max_length=32)),
                ('salary', models.CharField(blank=True, default='', help_text="Formatted salary text, e.g. '25,000 ETB monthly'.", max_length=255)),
                ('experience_level', models.CharField(blank=True, default='', help_text='Entry / Junior / Mid / Senior (when available).', max_length=32)),
                ('sector_name', models.CharField(blank=True, default='', help_text='Raw sector/category name from the source.', max_length=255)),
                ('skills', models.JSONField(blank=True, default=list, help_text="Skill names, e.g. ['React', 'Node.js'].")),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 of title|company|location|job_type|url.', max_length=64)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('job_number', models.PositiveIntegerField(blank=True, help_text='Per-day sequential number (01, 02, ...).', null=True)),
                ('numbered_on', models.DateField(blank=True, help_text='Local day this item was numbered on.', null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='The source-specific detail row fields (raw).')),
            ],
            options={
                'ordering': ['-numbered_on', 'job_number'],
                'indexes': [models.Index(fields=['source_slug', 'is_active'], name='norm_src_active_idx'), models.Index(fields=['updated_at'], name='norm_updated_at_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_slug', 'external_id'), name='uniq_norm_source_external_id')],
            },
        ),
    ]
