# Generated by Django 6.1 on 2026-10-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_normalizedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapelog',
            name='unstable_status',
            field=models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', help_text="Worst status across the day's unstable/flaky runs.", max_length=16),
        ),
        migrations.AddField(
            model_name='source',
            name='is_stable',
            field=models.BooleanField(default=True, help_text='If false, failures from this source will not cause the master day log or sweep to be marked as failed.'),
        ),
        migrations.AlterField(
            model_name='scrapelog',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', help_text="Worst status across the day's stable runs.", max_length=16),
        ),
        migrations.AlterField(
            model_name='scrapercreditusage',
            name='service',
            field=models.CharField(choices=[('scrapedo', 'ScrapeDo'), ('scrapebadger', 'ScrapeBadger'), ('zenrows', 'ZenRows'), ('scraperapi', 'ScraperAPI'), ('scrapfly', 'ScrapFly'), ('jina', 'JinaReader'), ('firecrawl', 'Firecrawl'), ('curl_cffi', 'CurlCffi'), ('playwright', 'Playwright')], max_length=20),
        ),
    ]
