# Generated by Django 6.1 on 2026-10-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_scrapelog_unstable_status_source_is_stable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapercreditusage',
            name='service',
            field=models.CharField(choices=[('jina', 'JinaReader'), ('firecrawl', 'Firecrawl'), ('curl_cffi', 'CurlCffi'), ('playwright', 'Playwright'), ('scrapedo_one', 'ScrapeDoOne'), ('scrapedo_two', 'ScrapeDoTwo'), ('scrapedo_three', 'ScrapeDoThree'), ('zenrows_one', 'ZenRowsOne'), ('zenrows_two', 'ZenRowsTwo'), ('zenrows_three', 'ZenRowsThree'), ('scraperapi_one', 'ScraperAPIOne'), ('scraperapi_two', 'ScraperAPITwo'), ('scraperapi_three', 'ScraperAPIThree'), ('scrapfly_one', 'ScrapFlyOne'), ('scrapfly_two', 'ScrapFlyTwo'), ('scrapfly_three', 'ScrapFlyThree')], max_length=20),
        ),
    ]
