# Generated by Django 6.1 on 2026-10-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_scrapercreditusage_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_text', models.CharField(help_text="e.g. 'Technician jobs belong in Manufacturing unless explicitly IT.'", max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Classification Rule',
                'verbose_name_plural': 'AI Classification Rules',
            },
        ),
    ]
